# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MyTools
                                 A QGIS plugin
 QGIS plugin to access my favorite tools
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-14
        copyright            : (C) 2020 by Patricio Soriano :: SIGdeletras.com
        email                : pasoriano@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MyTools class from file MyTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .my_tools import MyTools
    return MyTools(iface)
